import "../css/style.css";

const Weapons = [
  {
    name: "Blood Hound's Fang",
    Tier: "Unique",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "Blood",
    Overall: "S",
  },
  {
    name: "Rivers of  Blood",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "High",
    Status: "Blood",
    Overall: "S",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Broadsword",
    Tier: "Common",
    Scaling: "Strength",
    StatRequirement: "Low",
    Status: "None",
    Overall: "C",
  },
  {
    name: "Lusat's Glinstone Staff",
    Tier: "Unique",
    Scaling: "Intelligence",
    StatRequirement: "High",
    Status: "None",
    Overall: "S",
  },
  {
    name: "Dracon Communion Seal",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  v,
];
