
const Weapons = [
  {
    name: "Blood Hound's Fang",
    Tier: "Unique",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "Blood",
    Overall: "S",
  },
  {
    name: "Rivers of  Blood",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "High",
    Status: "Blood",
    Overall: "S",
  },
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Broadsword",
    Tier: "Common",
    Scaling: "Strength",
    StatRequirement: "Low",
    Status: "None",
    Overall: "C",
  },
  {
    name: "Lusat's Glinstone Staff",
    Tier: "Unique",
    Scaling: "Int",
    StatRequirement: "High",
    Status: "None",
    Overall: "S",
  },
  {
    name: "Dracon Communion Seal",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Reduvia",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "Low",
    Status: "Bleed",
    Overall: "A",
  },
  {
    name: "Bolt of Gransax",
    Tier: "Legendary",
    Scaling: "Dex",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Cross-Naginata",
    Tier: "Common",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "Bleed",
    Overall: "B",
  },
  {
    name: "Commander's Standard",
    Tier: "Unique",
    Scaling: "Strength",
    StatRequirement: "Mid",
    Status: "None",
    Overall: "B",
  },
  {
    name: "Lance",
    Tier: "Common",
    Scaling: "Strength",
    StatRequirement: "Mid",
    Status: "None",
    Overall: "C",
  },
  {
    name: "Mohgwyn's Sacred Spear",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "High",
    Status: "Bleed",
    Overall: "S",
  },
  {
    name: "Wonged Scythe",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "Bleed",
    Overall: "A",
  },
  {
    name: "Eleonora's Poleblade",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "High",
    Status: "Bleed",
    Overall: "A",
  },
  {
    name: "Godskin Peeler",
    Tier: "Unique",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "None",
    Overall: "A",
  },
  {
    name: "Club",
    Tier: "Common",
    Scaling: "Strength",
    StatRequirement: "Low",
    Status: "None",
    Overall: "D",
  },
  {
    name: "Ringed Finger",
    Tier: "Unique",
    Scaling: "Strength",
    StatRequirement: "Low",
    Status: "None",
    Overall: "B",
  },
  {
    name: "Varre's Bouquet",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "High",
    Status: "Bleed",
    Overall: "A",
  },
  {
    name: "Rotten Battle Hammer",
    Tier: "Unique",
    Scaling: "Strength",
    StatRequirement: "Mid",
    Status: "Scarlet Rot",
    Overall: "B",
  },
  {
    name: "Flail",
    Tier: "Common",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "None",
    Overall: "D",
  },
  {
    name: "Grafted Dragon",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
  },
];

export {Weapons};