const Weapons = [
  {
    name: "Blood Hound's Fang",
    Tier: "Unique",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "Blood",
    Overall: "S",
    image: "./PICS/Elden_Ring_Bloodhounds_Fang.webp",
  },    
  {
    name: "Broadsword",
    Tier: "Common",
    Scaling: "Strength",
    StatRequirement: "Low",
    Status: "None",
    Overall: "C",
    image: "./PICS/ER_Icon_weapon_Broadsword.webp",
  },
  {
    name: "Lusat's Glinstone Staff",
    Tier: "Unique",
    Scaling: "Int",
    StatRequirement: "High",
    Status: "None",
    Overall: "S",
    image: "./PICS/lusat.png",
  },  
  {
    name: "Golden Halbred",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
    image: "./PICS/ER_Icon_weapon_Golden_Halberd.webp",
  },
  {
    name: "Rivers of  Blood",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "High",
    Status: "Blood",
    Overall: "S",
    image: "./PICS/ER_Icon_weapon_Rivers_of_Blood.webp",
  },

  {
    name: "Golden Order Seal",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
    image: "./PICS/ER_Icon_weapon_Golden_Order_Seal.webp",
  },
  {
    name: "Falcion",
    Tier: "Common",
    Scaling: "Dex",
    StatRequirement: "Low",
    Status: "None",
    Overall: "C",
    image: "./PICS/Elden_Ring_Falchion.webp",
  },
  {
    name: "Bolt of Gransax",
    Tier: "Legendary",
    Scaling: "Dex",
    StatRequirement: "High",
    Status: "None",
    Overall: "A",
    image: "./PICS/ER_Icon_weapon_Bolt_of_Gransax.webp",
  },
  {
    name: "Cross-Naginata",
    Tier: "Common",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "Bleed",
    Overall: "B",
    image: "./PICS/Elden_Ring_Cross-Naginata.webp",
  },
  {
    name: "Commander's Standard",
    Tier: "Unique",
    Scaling: "Strength",
    StatRequirement: "Mid",
    Status: "None",
    Overall: "B",
    image: "./PICS/Elden_Ring_Commanders_Standard.webp",
  },
  {
    name: "Lance",
    Tier: "Common",
    Scaling: "Strength",
    StatRequirement: "Mid",
    Status: "None",
    Overall: "C",
    image: "./PICS/ER_Icon_weapon_Lance.webp",
  },
  {
    name: "Mohgwyn's Sacred Spear",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "High",
    Status: "Bleed",
    Overall: "S",
    image: "./PICS/mohg'sspear.png",
  },
  {
    name: "Winged Scythe",
    Tier: "Unique",
    Scaling: "Faith",
    StatRequirement: "High",
    Status: "Bleed",
    Overall: "A",
    image: "./PICS/winged.png",
  },
  {
    name: "Eleonora's Poleblade",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "High",
    Status: "Bleed",
    Overall: "A",
    image: "./PICS/image-removebg-preview.png",
  },
  {
    name: "Raptor Talons",
    Tier: "Common",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "Bleed",
    Overall: "B",
    image: "./PICS/ER_Icon_weapon_Raptor_Talons.webp",
  },
  {
    name: "Club",
    Tier: "Common",
    Scaling: "Strength",
    StatRequirement: "Low",
    Status: "None",
    Overall: "D",
    image: "./PICS/ER_Icon_weapon_Club.webp",
  },
  {
    name: "Ringed Finger",
    Tier: "Unique",
    Scaling: "Strength",
    StatRequirement: "Low",
    Status: "None",
    Overall: "B",
    image: "./PICS/ER_Icon_weapon_Ringed_Finger.webp",
  },
  {
    name: "Varre's Bouquet",
    Tier: "Unique",
    Scaling: "Arc",
    StatRequirement: "High",
    Status: "Bleed",
    Overall: "A",
    image: "./PICS/a6fd8fe462fd0d629e5056dc54f450e8-removebg-preview (1).png",
  },
  {
    name: "Rotten Battle Hammer",
    Tier: "Unique",
    Scaling: "Strength",
    StatRequirement: "Mid",
    Status: "Scarlet Rot",
    Overall: "B",
    image: "./PICS/ER_Icon_weapon_Rotten_Battle_Hammer.webp",
  },
  {
    name: "Flail",
    Tier: "Common",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "None",
    Overall: "D",
    image: "./PICS/ER_Icon_weapon_Flail.webp",
  },
  {
    name: "Long Bow",
    Tier: "Common",
    Scaling: "Dex",
    StatRequirement: "Mid",
    Status: "None",
    Overall: "B",
    image: "./PICS/ER_Icon_weapon_Longbow.webp",
  },
];

export { Weapons };
